### PR TITLE
create first draft of collaborators

### LINKED ISSUE #57: Add Collaborations
Create a section for Collaborations of EVERSE

### PR DESCRIPTION
**Pull request by aspaor**
Closes #57

### CODE REVIEW

**Comment by SanjeAntona** [comment]
concering the faircore4eosc logo: requested one where eosc is on top, like here: 

best as svg

tip for logo adjustment (for centred alignment): go to a svg editor (Inkscape, adobe), add more space around it and centre the logo

**Comment by aspaor** [comment]
Hi Sanje, thank you for your instructions. I uploaded some first info and tomorrow I will reshape the logos as you suggested.

**Comment by aspaor** [comment]
Hi @SanjeAntona , I uploaded small changes to the two profiles of collaborations and I fixed some typos that I have found in Consortium tab as well. In addition I changed the image of SciLifeLab to have better resolution. For   FAIRCORE4EOSC we sent email and we are waiting for better resolution logos.  I will update the image of FAIRCORE4EOSC as soon as possible. Thank you for your guidance.

**Review by SanjeAntona — CHANGES_REQUESTED** [review]
Looks good overall.
In case you get the proposed logo from faircore4eosc please change it.
And please add one sentence as an introduction between the "Collaborators" and "Collaboration Partners".

**Comment by aspaor** [comment]
Hi @SanjeAntona  I made some additions as you suggested. Hope now looks ready. Please let me know if is there anything else that I can modify.

**Review by graeme-a-stewart — APPROVED** [review]

**Comment by graeme-a-stewart** [comment]
Thank you @aspaor !

**Pull request merged**
