### PR TITLE
update to WP2 description text to be more accesible to readers/visitors

### PR DESCRIPTION
**Pull request by SanjeAntona**
I've changed the WP2 description text to me more readable and accessible to readers/visitors.

Please check if it's alright and let me know about any changes.

### CODE REVIEW

**Review by egpbos — COMMENTED** [review]
Thanks for this effort Sanje! Your formulation is indeed more readable. However, I feel like in the translation, we lost some subtleties that we need to address. We should probably discuss this at a next WP2 meeting. Just to name one example: FAIR is one of currently 4 categories of quality criteria, and probably a smaller one at that, so focusing on it alone may give a wrong impression.

**Comment by SanjeAntona** [comment]
hi @egpbos thanks for the feedback. happy to improve the description any further.
the next WP2 meeting is next wednesday (10th July) at 15.00 CEST?

**Comment by egpbos** [comment]
Yep, that's right! Will you be able to attend? If not, we can always send you the comments made afterwards, of course.

**Comment by SanjeAntona** [comment]
yeah, I'm free next week, so I'll join your call

**Comment by egpbos** [comment]
Hi Sanje, sorry for taking so long on this. I think with the following minor change to your suggestion (only the first sentence of the second paragraph), we can merge this!

> Each research community has its own techniques for computing-based research. Work package 2 works towards assessing all these approaches and developing common grounds for best practices applicable to all developers. The *Research Software Quality kit* [(RSQkit)](/services/rsqkit/) will be a knowledge hub that collects existing expertise while ensuring improvement.
> 
> The curated best practices are gathered across four pillars: technical quality, FAIR principles, Openness and Software Sustainability. They are used to find a common framework and act as measurables for indicators of software quality. Woven into the RSQkit, these practices will be incorporated into the future Virtual Institute driven by WP1.

Do you want to reopen the PR or do you want to do a new one?

**Comment by SanjeAntona** [comment]
Hi Patrick, 

Thanks for the changes, I’ll implement them.
And I’ll make a new PR for it, not sure if I’ll get to it today, but latest next week.

All the best
Sanje

**Pull request closed without merging**
